name: taskflow
services:
  tempo:
    # Tempo "classic" monolithic config (sans Kafka obligatoire)
    image: grafana/tempo:2.9.0
    ports:
      - "3200:3200" # API/UI (Grafana interroge ce port)
    volumes:
      - ./infra/tempo/tempo.yml:/etc/tempo/tempo.yml
    command: ["-config.file=/etc/tempo/tempo.yml"]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888" # métriques internes du collector (scrapées par Prometheus)
    volumes:
      - ./infra/otel/config.yml:/etc/otel/config.yml
    command: ["--config=/etc/otel/config.yml"]
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3300:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
      - tempo
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./infra/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: ["-config.file=/etc/loki/local-config.yaml"]

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./infra/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["-config.file=/etc/promtail/config.yml"]
    depends_on:
      - loki

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
