services:
  api:
    image: zouzouprod291/notes-api:v2
    ports:
      - "${API_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db-data:
