apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: staging
type: Opaque
stringData:
  POSTGRES_DB: "taskflow"
  POSTGRES_USER: "taskflow"
  POSTGRES_PASSWORD: "taskflow123"