apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-cm
  namespace: staging
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskflow"
  DB_USER: "taskflow"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  TASK_SERVICE_PORT: "3002"
  LOG_LEVEL: "info"
